Update linter.yml

diff --git a/.github/workflows/linter.yml b/.github/workflows/linter.yml
--- a/.github/workflows/linter.yml
+++ b/.github/workflows/linter.yml
@@ -12,22 +12,26 @@ jobs:
   pr-lint:
     runs-on: ubuntu-latest
     steps:
-      - uses: morrisoncole/pr-lint-action@v1.7.0
-        with:
-          # Note: if you have branch protection rules enabled, the `GITHUB_TOKEN` permissions
-          # won't cover dismissing reviews. Your options are to pass in a custom token
-          # (perhaps by creating some sort of 'service' user and creating a personal access
-          # token with the correct permissions) or to turn off `on-failed-regex-request-changes`
-          # and use action failure to prevent merges instead (with
-          # `on-failed-regex-fail-action: true`). See:
-          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
-          # https://docs.github.com/en/rest/pulls/reviews#dismiss-a-review-for-a-pull-request
-          repo-token: "${{ secrets.GITHUB_TOKEN }}"
-          title-regex: "#[eE][xX]-[0-9]+"
-          on-failed-regex-fail-action: false
-          on-failed-regex-create-review: true
-          on-failed-regex-request-changes: false
-          on-failed-regex-comment:
-            "This is just an example. Failed regex: `%regex%`!"
-          on-succeeded-regex-dismiss-review-comment:
-            "This is just an example. Success!"
+      - name: Checkout
+        uses: actions/checkout@v3
+
+      - name: Setup Node
+        uses: actions/setup-node@v3
+
+      - name: Lint JavaScript and Typescript with ESLint
+        run: npm run lint
+        env:
+          CI: true
+
+      - name: Verify there's no Prettier diff
+        run: |
+          npm run prettier -- --loglevel silent
+          if ! git diff --name-only --exit-code; then
+            # shellcheck disable=SC2016
+            echo 'Error: Prettier diff detected! Please run `npm run prettier` and commit the changes.'
+            exit 1
+          fi
+
+      - name: Run unused style searcher
+        shell: bash
+        run: ./.github/scripts/findUnusedKeys.sh
